/*************************************************************************

  This file is part of the PicoNut project.

  Copyright (C)      2025 Claus Janicher <claus.janicher@tha.de>
      Technische Hochschule Augsburg, Technical University of Applied Sciences Augsburg


  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation and/or
     other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 *************************************************************************/

// TBD+: Remove this file and let the SystemC modell be generated by 'pn-memgen'.

#include "membrana_hw_emem.h"
#include <stdint.h>

#ifndef __SYNTHESIS__
#include <pn_elf_reader.h>
#endif

void m_membrana_hw_emem::pn_trace(sc_trace_file* tf, int level)
{

    // Ports ...
    PN_TRACE(tf, clka);
    PN_TRACE(tf, clkb);

    PN_TRACE(tf, wea);
    PN_TRACE(tf, ena);

    PN_TRACE(tf, addra);
    PN_TRACE(tf, dia);
    PN_TRACE(tf, doa);

    PN_TRACE(tf, web);
    PN_TRACE(tf, enb);

    PN_TRACE(tf, addrb);
    PN_TRACE(tf, dib);
    PN_TRACE(tf, dob);
}

void m_membrana_hw_emem::proc_clk_ram_port_a()
{

    sc_uint<32> combData;

    while(1)
    {

        wait();

        // Port A

        if(ena.read() == 1)
        {

            if((((uint32_t(addra.read())) - ((PN_CFG_CPU_RESET_ADR) >> 2)) < 0x00) || (((uint32_t)(addra.read()) - ((PN_CFG_CPU_RESET_ADR) >> 2)) >= PN_CFG_MEMBRANA_EMEM_SIZE))
            {
                PN_ERROR("Wrong memory access!");
            }
            combData = ram[(uint32_t)(addra.read()) - (((uint32_t)(PN_CFG_CPU_RESET_ADR) >> 2))];

            // check if nucleus writes into code area
            if(wea.read() == 1)
            {
                if(addra.read() > ((uint32_t)(PN_CFG_CPU_RESET_ADR) + 0x0001FFFF))
                    PN_INFO("!!! WRITING CODE ERROR !!!");
            }

            doa = combData;

            for(uint i = 0; i < 4; i++)
            {
                if(wea.read()[i] == 1)
                {
                    combData &= ~(0xffU << (8 * i));
                    combData |= (dia.read() & (0xffU << (8 * i)));
                }
            }
            ram[(uint32_t)addra.read() - ((uint32_t)(PN_CFG_CPU_RESET_ADR) >> 2)] = combData;
        }
    }
}

void m_membrana_hw_emem::proc_clk_ram_port_b()
{

    sc_uint<32> combData;

    while(1)
    {
        wait();
        // Port B

        if(enb == 1)
        {

            combData = ram[addrb.read() - PN_CFG_CPU_RESET_ADR];
            dob = combData;

            for(uint i = 0; i < 4; i++)
            {

                if(web.read()[i] == 1)
                {
                    combData &= ~(0xffU << (8 * i));
                    combData |= (dib.read() & (0xffU << (8 * i)));
                }
            }
            ram[addra.read() - PN_CFG_CPU_RESET_ADR] = combData;
        }
    }
}

#ifndef __SYNTHESIS__

void m_membrana_hw_emem::load_elf(const std::string& elf_file_path)
{
    if(elf_file_path.empty())
    {
        PN_WARNING("ELF file path is empty. Leaving RAM uninitielized ...");
        return;
    }

    pn_c_elf_reader elf_reader;
    elf_reader.read_file(elf_file_path.c_str());

    PN_INFOF(("ELF start address: 0x%x; ELF size: 0x%x", elf_reader.get_size(), elf_reader.get_base_addr()));

    if(elf_reader.get_size() == 0 || elf_reader.get_base_addr() == UINT32_MAX)
    {
        PN_ERROR("ELF file size or start address is zero or invalid - check ELF file and reader.");
        return;
    }

    unsigned char* memory_to_load = elf_reader.get_memory();

    size_t size = elf_reader.get_size();

    // Calculate the number of 32-bit words required
    size_t num_words = (size + 3) / 4; // Round up if not a multiple of 4

    // Fill the sc_vector with 32-bit words from memory_to_load
    for(size_t i = 0; i < num_words; ++i)
    {
        uint32_t word = 0;

        // Loop through up to 4 bytes at a time and construct a 32-bit word
        for(size_t j = 0; j < 4 && (i * 4 + j) < size; ++j)
        {
            word |= (static_cast<uint32_t>(memory_to_load[i * 4 + j]) & 0xFF) << (8 * j);
        }

        // Assign the constructed 32-bit word to the ram
        ram[i] = word;
    }

    PN_INFO("Blockram successfully initialized with ELF-File! ");
}

#endif
