/*************************************************************************

  This file is part of the PicoNut project.

  Copyright (C)      2025 Claus Janicher <claus.janicher@tha.de>
                     2026 Hermann Zoha <hermann.zoha@web.de>
      Technische Hochschule Augsburg, Technical University of Applied Sciences Augsburg


  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation and/or
     other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 *************************************************************************/

/**
 * @fn SC_MODULE(m_membrana_hw_emem)
 * @author Claus Janicher, Gundolf Kiefer
 * @brief Blockram memory module for the membrana_hw.
 *
 * This module is a dual-port blockram that is being used for code and memory storage of the piconut system.
 *
 *
 *
 * @par Ports:
 * @param[in] clka clock a of the module
 * @param[in] clkb clock b of the module
 * @param[in] reset reset of the module
 * @param[in] wea <4> Bit write enable for port a
 * @param[in] web <4> Bit write enable for port b
 * @param[out] doa <32> Bit data output port a
 * @param[out] dob <32> Bit data output port b
 * @param[in] dia <32> Bit data input port a
 * @param[in] dib <32> Bit data input port b
 * @param[in] ena enable signal for port a
 * @param[in] enb enable signal for port b
 */

// TBD+: Remove this file and let the SystemC modell be generated by 'pn-memgen'.

#ifndef __MEMBRANA_HW_EMEM_H__
#define __MEMBRANA_HW_EMEM_H__

#include <piconut.h>

SC_MODULE(m_membrana_hw_emem)
{
public:
    // Ports ...
    sc_in<bool> PN_NAME(clka);
    sc_in<bool> PN_NAME(clkb);

    sc_in<sc_uint<4>> PN_NAME(wea); // data width is fixed to 32bit -> 4 byte enables
    sc_in<sc_uint<4>> PN_NAME(web); // data width is fixed to 32bit -> 4 byte enables
    sc_in<bool> PN_NAME(ena);       // enable signal for blockram a
    sc_in<bool> PN_NAME(enb);       // enable signal for blockram b

    sc_in<sc_uint<32>> PN_NAME(addra); // blockram a address
    sc_in<sc_uint<32>> PN_NAME(addrb); // blockram b address
    sc_in<sc_uint<32>> PN_NAME(dia);   // blockram a data in
    sc_in<sc_uint<32>> PN_NAME(dib);   // blockram b data in
    sc_out<sc_uint<32>> PN_NAME(doa);  // blockram a data out
    sc_out<sc_uint<32>> PN_NAME(dob);  // blockram b data out

    // initialize the size of the used memory
    sc_uint<32> ram[PN_CFG_MEMBRANA_EMEM_SIZE / 4];

    // Constructor...
    SC_CTOR(m_membrana_hw_emem)
    {
        SC_CTHREAD(proc_clk_ram_port_a, clka.pos());
        SC_CTHREAD(proc_clk_ram_port_b, clkb.pos());

#ifndef __SYNTHESIS__
        load_elf(pn_cfg_application_path.c_str());
#endif
    }

    // Functions...
    void pn_trace(sc_trace_file * tf, int level = 1);

    // Processes...
    void proc_clk_ram_port_a();
    void proc_clk_ram_port_b();

    // This module has an alternative Verilog implementation
    PN_PRESYNTHESIZED;

protected:
#ifndef __SYNTHESIS__
    /**
     * @brief Loads an ELF (Executable and Linkable Format) file into memory.
     * @param elf_file_path Path to the ELF binary file.
     */
    void load_elf(const std::string& elf_file_path);
#endif
};

#endif // __MEMBRANA_HW_EMEM_H__
