/*************************************************************************

  This file is part of the PicoNut project.

  Copyright (C)      2025 Claus Janicher <claus.janicher@tha.de>
      Technische Hochschule Augsburg, Technical University of Applied Sciences Augsburg


  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation and/or
     other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 *************************************************************************/

/**
 * @fn SC_MODULE(m_membrana_hw_emem)
 * @author Claus Janicher, Gundolf Kiefer
 * @brief Blockram memory module for the membrana_hw.
 *
 * This module is a dual-port blockram that is being used for code and memory storage of the piconut system.
 *
 *
 *
 * @par Ports:
 * @param[in] clka clock a of the module
 * @param[in] clkb clock b of the module
 * @param[in] reset reset of the module
 * @param[in] wea <4> Bit write enable for port a
 * @param[in] web <4> Bit write enable for port b
 * @param[out] doa <32> Bit data output port a
 * @param[out] dob <32> Bit data output port b
 * @param[in] dia <32> Bit data input port a
 * @param[in] dib <32> Bit data input port b
 * @param[in] ena enable signal for port a
 * @param[in] enb enable signal for port b
 */


// TBD+: Remove this file and let the SystemC modell be generated by 'pn-memgen'.



#ifndef __MEMBRANA_HW_EMEM_H__
#define __MEMBRANA_HW_EMEM_H__

#include <piconut.h>


#ifndef __SYNTHESIS__
#include "elf_reader.h"
#endif


SC_MODULE(m_membrana_hw_emem) {
public:
    // Ports ...
    sc_in<bool> PN_NAME(clka);
    sc_in<bool> PN_NAME(clkb);

    sc_in<sc_uint<4>> PN_NAME(wea); // data width is fixed to 32bit -> 4 byte enables
    sc_in<sc_uint<4>> PN_NAME(web); // data width is fixed to 32bit -> 4 byte enables
    sc_in<bool> PN_NAME(ena);       // enable signal for blockram a
    sc_in<bool> PN_NAME(enb);       // enable signal for blockram b

    sc_in<sc_uint<32>> PN_NAME(addra); // blockram a address
    sc_in<sc_uint<32>> PN_NAME(addrb); // blockram b address
    sc_in<sc_uint<32>> PN_NAME(dia);   // blockram a data in
    sc_in<sc_uint<32>> PN_NAME(dib);   // blockram b data in
    sc_out<sc_uint<32>> PN_NAME(doa);  // blockram a data out
    sc_out<sc_uint<32>> PN_NAME(dob);  // blockram b data out

    // initialize the size of the used memory
    sc_uint<32> ram[PN_CFG_MEMBRANA_EMEM_SIZE/4];

    // Constructor...

    SC_CTOR (m_membrana_hw_emem) {


        SC_CTHREAD(proc_clk_ram_port_a, clka.pos());
        SC_CTHREAD(proc_clk_ram_port_b, clkb.pos());

#ifndef __SYNTHESIS__
        c_elf_reader c_elf_reader(pn_cfg_application_path);

        std::cout << "Size of ElfFile " << c_elf_reader.size << " c_elf_reader.startArd " << c_elf_reader.start_adr << std::endl;

        if(c_elf_reader.size == 0 || c_elf_reader.start_adr == UINT32_MAX)
        {
            std::cerr << "ELF file size or start address is zero or invalid - check ELF file and reader." << std::endl;
            return;
        }

        const char* memory_to_load = c_elf_reader.get_memory();

        size_t size = c_elf_reader.size;

        // Calculate the number of 32-bit words required
        size_t num_words = (size + 3) / 4; // Round up if not a multiple of 4

        // Fill the sc_vector with 32-bit words from memory_to_load
        for(size_t i = 0; i < num_words; ++i)
        {
            uint32_t word = 0;

            // Loop through up to 4 bytes at a time and construct a 32-bit word
            for(size_t j = 0; j < 4 && (i * 4 + j) < size; ++j)
            {
                word |= (static_cast<uint32_t>(memory_to_load[i * 4 + j]) & 0xFF) << (8 * j);
            }

            // Assign the constructed 32-bit word to the ram
            ram[i] = word;
        }

        std::cout << "Blockram successfully initialized with ELF-File! " << std::endl;
#endif // sc_tool software guard
    }

    // Functions...
    void pn_trace(sc_trace_file * tf, int level = 1);

    // Processes...
    void proc_clk_ram_port_a();
    void proc_clk_ram_port_b();

    // This module has an alternative Verilog implementation
    PN_PRESYNTHESIZED;

protected:
};




#endif // __MEMBRANA_HW_EMEM_H__
