#  -----------------------------------------------------------------------------
#
#  This file is part of the PicoNut project.
#
#  Copyright (C) 2025 Johannes Hofmann <johannes.hofmann1@tha.de>
#                     Tristan Kundrat <tristan.kundrat@tha.de>
#      Technische Hochschule Augsburg, Technical University of Applied Sciences Augsburg
#
#
#  --------------------- LICENSE -----------------------------------------------
#  Redistribution and use in source and binary forms, with or without modification,
#  are permitted provided that the following conditions are met:
#
#  1. Redistributions of source code must retain the above copyright notice, this
#     list of conditions and the following disclaimer.
#
#  2. Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation and/or
#     other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
#  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  -----------------------------------------------------------------------------


ARG PREV_IMAGE=piconut_raw
FROM ${PREV_IMAGE} AS riscv_base

USER root

################################################################################
# Environment

# RISC-V GNU Compiler Toolchain
ENV RISCV="/opt/riscv"
ENV RISCV_TOOLCHAIN_VERSION="2026.02.13"

# RISC-V Compliance Test Framework
ENV RISCOF_HOME="/opt/riscof"
ENV SAILC_HOME="/opt/sail_riscv-Linux-x86_64"

################################################################################

#### RISC-V  #########################################################
# get new gcc 12.2.0 for test
RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    autotools-dev \
    curl \
    python3 \
    python3-pip \
    python3-tomli \
    libmpc-dev \
    libmpfr-dev \
    libgmp-dev \
    gawk \
    build-essential \
    bison \
    flex \
    texinfo \
    gperf \
    libtool \
    patchutils \
    bc \
    zlib1g-dev \
    libexpat-dev \
    ninja-build \
    git \
    cmake \
    libglib2.0-dev \
    libslirp-dev \
    libncurses-dev \
    python-is-python3 \
    # For Spike
    device-tree-compiler \
    libboost-regex-dev \
    libboost-system-dev && \
    \
    rm -rf /var/lib/apt/lists/* && \
    apt-get -y autoremove && \
    apt-get -y autoclean && \
    rm -rf /var/lib/apt/lists/*

# RISC-V GNU Compiler Toolchain
RUN mkdir -p /build && \
    cd /build && \
    # clone repository
    git clone https://github.com/riscv-collab/riscv-gnu-toolchain.git && \
    cd riscv-gnu-toolchain && \
    git checkout ${RISCV_TOOLCHAIN_VERSION} && git submodule update --init --recursive && \
    # build toolchain
    mkdir -p ${RISCV} && \
    ./configure --prefix=${RISCV} --with-multilib-generator="rv32i-ilp32--;rv32im-ilp32--;rv32ima-ilp32--;rv32ia-ilp32--;rv32im_zve32x-ilp32--" && \
    make -j$(nproc) && \
    cd / && \
    rm -rf /build

ENV PATH="${RISCV}/bin:$PATH"

# Spike RISC-V ISA Simulator for rv32 target
RUN mkdir -p /build && \
    cd /build && \
    git clone https://github.com/riscv-software-src/riscv-isa-sim.git && \
    cd riscv-isa-sim && \
    mkdir build && \
    cd build && \
    mkdir -p ${RISCV} && \
    ../configure --prefix=${RISCV} --with-target=riscv32-unknown-elf && \
    make -j$(nproc) && \
    make install && \
    cd / && \
    rm -rf /build

# RISC-V Proxy Kernel and Boot Loader
RUN mkdir -p /build && \
    cd /build && \
    git clone https://github.com/riscv-software-src/riscv-pk.git && \
    cd riscv-pk && \
    mkdir build && \
    cd build && \
    mkdir -p ${RISCV} && \
    # Bare-metal + rv32 (default: rv64)
    ../configure --prefix=${RISCV} --host=riscv64-unknown-elf --with-arch=rv32i_zicsr_zifencei && \
    make -j$(nproc) && \
    make install && \
    cd / && \
    rm -rf /build

##### Dev Tools ################################################################

# GtkWave Filter
# Filter for RISC-V instructions 

RUN apt-get update && apt-get install -y --no-install-recommends \
    clang llvm-dev && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get -y autoremove && \
    apt-get -y autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /build && \
    cd /build && \
    git clone https://github.com/FurryAcetylCoA/gtkwave-filter-process-RISC && \
    cd gtkwave-filter-process-RISC && \
    make && \
    mkdir -p /opt/gtkwave-filter-process-RISC && \
    cp LICENSE /opt/gtkwave-filter-process-RISC/ && \
    cp -r bin/* /opt/gtkwave-filter-process-RISC/ && \
    cd / && \
    rm -rf /build/


##### RISC-V Compliance Test Framework #########################################

# install pipx for python package management of riscof
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    pipx && \
    \
    rm -rf /var/lib/apt/lists/* && \
    apt-get -y autoremove && \
    apt-get -y autoclean && \
    rm -rf /var/lib/apt/lists/*

# install riscof and sailc for compliance test framework
RUN pipx ensurepath && \
    PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/opt/riscof/bin pipx install riscof && \
    wget -c https://github.com/riscv/sail-riscv/releases/download/0.7/sail_riscv-Linux-x86_64.tar.gz -O - | tar -xz -C /opt

# add compliance test framework to path
ENV PATH="${SAILC_HOME}/bin:${RISCOF_HOME}/bin:${PATH}"



##### Float Tests #############################################################

# Install float number test generation tool.
# See: https://www.jhauser.us/arithmetic/SoftFloat-3/doc/SoftFloat-source.html
# See: https://www.jhauser.us/arithmetic/TestFloat-3/doc/TestFloat-source.html

RUN mkdir -p /build && \
    cd /build && \
    wget https://www.jhauser.us/arithmetic/SoftFloat-3e.zip && \
    unzip SoftFloat-3e.zip && \
    cd SoftFloat-3e/build/Linux-x86_64-GCC && \
    make -j$(nproc) && \
    \
    cd /build && \
    wget https://www.jhauser.us/arithmetic/TestFloat-3e.zip && \
    unzip TestFloat-3e.zip && \
    cd TestFloat-3e/build/Linux-x86_64-GCC && \
    make -j$(nproc) && \
    cp testfloat_gen /usr/local/bin/ && \
    \
    cd / && \
    rm -rf /build/


################################################################################
