/* Auto-generated by gen_input_data.py -- do not edit by hand.
   Source text: 'Hello, how are you?'
   Tokenized length (incl. EOS): 7 / 256
*/
#include "llm_input_data.h"

const int32_t llm_input_data_000000[] = {
    133, 2737, 9, 5049, 17874, 16};
const size_t llm_input_data_000000_len = 6;

const int32_t* llm_input_data[] = {llm_input_data_000000};

const size_t llm_input_data_len[] = {llm_input_data_000000_len};
