"""
Tokenizes a source sentence with SentencePiece and emits a C header file
containing the encoder-stage input tensors, in the same
language_translation_input_data[] / language_translation_input_data_len[]
convention your main.cpp already expects (array-of-pointers + a parallel
byte-length array, so main.cpp's memcpy(..., data[i], len[i]) calls work
unchanged).

Usage:
    python gen_input_data.py "Hello, how are you?" \
        --spm source.spm \
        --out language_translation_input_data.h

Emits 3 arrays, matching encode.tflite's expected inputs:
    [0] input_ids  int32[256]
    [1] input_pos  int32[256]
    [2] pad_mask   float32[256]

IMPORTANT: the pad_mask sign convention (additive vs multiplicative) has not
been empirically confirmed against this model -- see --mask-mode below.
Default is additive (0.0 = attend, -1e9 = ignore), matching the Python
run_inference.py script we validated translation quality with. If your C++
output doesn't match the Python output, try --mask-mode multiplicative.
"""
import argparse
import sentencepiece as spm


MAX_LEN = 256
PAD_ID = 32000
EOS_ID = 0


def build_arrays(text: str, sp: spm.SentencePieceProcessor, mask_mode: str):
    ids = sp.encode(text, out_type=int) + [EOS_ID]
    seq_len = len(ids)
    if seq_len > MAX_LEN:
        raise ValueError(
            f"Tokenized input ({seq_len} tokens incl. EOS) exceeds MAX_LEN={MAX_LEN}. "
            "Use a shorter sentence."
        )

    input_ids = ids + [PAD_ID] * (MAX_LEN - seq_len)
    input_pos = list(range(MAX_LEN))

    if mask_mode == "additive":
        pad_mask = [0.0 if i < seq_len else -1e9 for i in range(MAX_LEN)]
    elif mask_mode == "multiplicative":
        pad_mask = [1.0 if i < seq_len else 0.0 for i in range(MAX_LEN)]
    else:
        raise ValueError(f"Unknown mask_mode: {mask_mode}")

    return input_ids, input_pos, pad_mask, seq_len


def format_int32_array(name: str, values):
    body = ", ".join(str(v) for v in values)
    return f"const int32_t {name}[{len(values)}] = {{ {body} }};"


def format_float_array(name: str, values):
    body = ", ".join(
        f"{v:.8g}f" if 'e' in f"{v:.8g}" or '.' in f"{v:.8g}" else f"{v:.8g}.f"
        for v in values
    )
    return f"const float {name}[{len(values)}] = {{ {body} }};"

def write_c_source(path: str, input_ids, input_pos, pad_mask, source_text: str, seq_len: int):
    with open(path, "w") as f:
        f.write("/* Auto-generated by gen_input_data.py -- do not edit by hand.\n")
        f.write(f"   Source text: {source_text!r}\n")
        f.write(f"   Tokenized length (incl. EOS): {seq_len} / {MAX_LEN}\n")
        f.write("*/\n")
        f.write("#include \"language_translation_input_data.h\"\n\n")

        f.write(format_int32_array("language_translation_input_ids", input_ids) + "\n\n")
        f.write(format_int32_array("language_translation_input_pos", input_pos) + "\n\n")
        f.write(format_float_array("language_translation_pad_mask", pad_mask) + "\n\n")

        f.write("const int8_t* const language_translation_input_data[3] = {\n")
        f.write("    (const int8_t*)language_translation_input_ids,\n")
        f.write("    (const int8_t*)language_translation_input_pos,\n")
        f.write("    (const int8_t*)language_translation_pad_mask,\n")
        f.write("};\n\n")

        f.write("const size_t language_translation_input_data_len[3] = {\n")
        f.write("    sizeof(language_translation_input_ids),\n")
        f.write("    sizeof(language_translation_input_pos),\n")
        f.write("    sizeof(language_translation_pad_mask),\n")
        f.write("};\n\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("text", help="Source-language sentence to translate")
    parser.add_argument("--spm", default="source.spm", help="Path to source SentencePiece model")
    parser.add_argument(
        "--out", default="language_translation_input_data.cpp", help="Output C source path"
    )
    parser.add_argument(
        "--mask-mode",
        choices=["additive", "multiplicative"],
        default="additive",
        help="pad_mask sign convention (default: additive)",
    )
    args = parser.parse_args()

    sp = spm.SentencePieceProcessor(model_file=args.spm)
    input_ids, input_pos, pad_mask, seq_len = build_arrays(args.text, sp, args.mask_mode)
    write_c_source(args.out, input_ids, input_pos, pad_mask, args.text, seq_len)

    print(f"Wrote {args.out}")
    print(f"  tokens ({seq_len}): {input_ids[:seq_len]}")


if __name__ == "__main__":
    main()
